---
- name: k8s test
  hosts: localhost
  connection: local
  vars_files:
    - cr_list
  tasks:
    - name: Deploy custom resource
      k8s:
        host: "{{ api_path }}"
        api_key: "{{ api_key }}"
        namespace: "{{ project_name }}"
        src: "{{ item.path }}"
        validate_certs: no
      loop: "{{ paths }}"
...
   
