---
- name: k8s test
  hosts: localhost
  connection: local
  vars_files:
    - cr_list
  tasks:
    - name: Deploy or update custom resources
      k8s:
        apply: yes
        namespace: "{{ project_name }}"
        src: "{{ item.path }}"
        validate_certs: no
      loop: "{{ paths }}"
...
   
