apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-claim
  labels:
    app: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs