apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-mariadb-storage-claim
  labels:
    app: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

  # storageClassName: nfs